- name: Stand up webapp container
  docker:
    name: dicetowertopten_webapp
    image: "quay.io/wilsonianb/dice_tower:{{deploy_environment}}"
    registry: "https://quay.io/v1/"
    email: "{{ lookup('env','QUAY_EMAIL') }}"
    username: "{{ lookup('env','QUAY_USERNAME') }}"
    password: "{{ lookup('env','QUAY_PASSWORD') }}"
    state: reloaded
    pull: always
    links:
      - dicetowertopten_postgres:postgres
    restart_policy: always
    ports:
      - "1337:1337"
    expose:
      - 1337
